[global]
plan    = "go-threads"
case    = "sync-threads"
builder = "docker:go"
runner  = "local:docker"
total_instances = 5
  [global.run]
  test_params = {records="10", verbose="1", test-timeout="2m"}

[[groups]]
id = "always-on"
instances = { count = 3 }

[[groups]]
id = "early-stopper"
instances = { count = 1 }
  [groups.run]
  test_params = {early-stop="true"}

[[groups]]
id = "late-joiner"
instances = { count = 1 }
  [groups.run]
  test_params = {late-start="true"}
