name: Publish gRPC Libs
on:
  release:
    types: [published]
  pull_request:
    branches:
      - master
jobs:

  publish_grpc_libs:
    name: Publish gRPC Libs
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Get latest tag
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Install build tools
        run: |
          apt-get update && apt-get install -y build-essential
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install protoc
        uses: Arduino/actions/setup-protoc@master
        with:
          version: '3.11.2'
      - name: Install Go protoc plugin
        run: |
          go get -u github.com/golang/protobuf/protoc-gen-go
      - name: Get JS dependencies
        run: |
          cd api/pb/javascript
          npm install
      - name: Get Dart dependencies
        run: |
          cd api/pb/dart
          pub get
          pub global activate protoc_plugin
      - name: Protoc generate API
        run: |
          cd api/pb
          make clean && make
      - name: Publish JS API
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          cd api/pb/javascript
          echo ${{ steps.latesttag.outputs.tag }}
          sed -i.bak "s/<version>/${{ steps.latesttag.outputs.tag }}/g" package.json
          npm publish
