name: Release
on:
  release:
    types: [created]
jobs:
  release-platform-builds:
    name: Release Builds
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out code
        uses: actions/checkout@v1
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -v -t -d ./...
      - name: Install gox
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get github.com/mitchellh/gox  
      - name: Compile
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          gox -osarch="linux/amd64 linux/386 linux/arm darwin/amd64 windows/amd64" -output="threadsd-{{.OS}}-{{.Arch}}" ./threadsd
          gox -osarch="linux/amd64 linux/386 linux/arm darwin/amd64 windows/amd64" -output="threads-{{.OS}}-{{.Arch}}" ./threads
      - name: Collect artifacts
        run: |
          VERSION=${GITHUB_REF##*/}
          OUT=release/cli
          mkdir -p ${OUT}
          mkdir -p install-threads
          cp LICENSE install-threads/
          cp dist/README.md install-threads/
          cp dist/install install-threads/
          declare -a arr=("darwin-amd64" "windows-amd64.exe" "linux-amd64" "linux-386" "linux-arm")
          for i in "${arr[@]}"
          do
              OSARCH=${i%.*}
              EXT=$([[ "$i" = *.* ]] && echo ".${i##*.}" || echo '')
              cp threadsd-${i} install-threads/threadsd${EXT}
              cp threads-${i} install-threads/threads${EXT}
              if [ "${EXT}" == ".exe" ]; then
                  zip -r go-threads_${VERSION}_${OSARCH}.zip install-threads
                  mv go-threads_${VERSION}_${OSARCH}.zip ${OUT}/
              else
                  tar -czvf go-threads_${VERSION}_${OSARCH}.tar.gz install-threads
                  mv go-threads_${VERSION}_${OSARCH}.tar.gz ${OUT}/
              fi
          done
          rm -rf install-threads
          echo $(ls ./release/cli)
      - name: Upload multiple assets to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'release/cli/go-threads_*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  android-client:
    name: Android Release
    runs-on: ubuntu-latest
    steps:
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install protoc
        uses: Arduino/actions/setup-protoc@master
        with:
          version: '3.11.2'
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.5
      - name: Check out code
        uses: actions/checkout@v1
      - name: Update Version
        run: |
          cd api/pb/android
          sed -i.bak "s/<version>/${GITHUB_REF##*/}/g" manifest.gradle
      - name: Install
        run: |
          cd api/pb/android
          ./gradlew threads:install
      - name: Publish
        env:
          BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        run: |
          cd api/pb/android
          ./gradlew threads:bintrayUpload
